import { MaterialUIProvider } from "@/shared/providers";
import type { Metadata } from "next";
import "./globals.css";
import { MainFooter, MainNavBar } from "@/shared/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{
          position: "relative",
        }}
      >
        <MaterialUIProvider>
          <MainNavBar />
          {children}
          <MainFooter />
        </MaterialUIProvider>
      </body>
    </html>
  );
}
